# ワークフロー名
name: update gist
env:
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:      
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3' # The Go version to download (if necessary) and use.
          
      - name: run
        run: |
          make run
