name: lint
on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - uses: actions/checkout@v4

      - name: golangci-lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run

      - name: govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck ./...
